server:
  port: 9000

spring:
  kafka:
    streams:
      application-id: my-streams-app
    topic: test-producer-consumer
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        schema:
          registry:
            url: http://localhost:8081
    consumer:
      group-id: myGroup

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver