server:
  port: 9001

spring:
  kafka:
    topic: test-producer-consumer
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/silicon
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver