server:
  port: 9000

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3307/silicon
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver