server:
  port: 9000

spring:
  kafka:
    topic: test-producer-consumer
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/maninder
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver