server:
  port: 9001
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://mysqldb:3306/silicon
    username: maninder
    password: maninder
    driver-class-name: com.mysql.cj.jdbc.Driver