server:
  port: 9002

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      use_sql_comments: true
      ddl-auto: update
      format_sql: true
      show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/wikimedia
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    topic: wikimedia_recentchange
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
